import { Colors } from "@/constants/Colors";
import { verticalScale } from "@/utils/responsive";
import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.bgPrimary,
    padding: 24,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    color: Colors.textPrimary,
    fontWeight: "600",
  },
  loadingSubtext: {
    marginTop: 8,
    fontSize: 14,
    color: Colors.textMuted,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.bgPrimary,
    padding: 24,
  },
  errorText: {
    fontSize: 20,
    color: Colors.red,
    fontWeight: "700",
    marginTop: 16,
  },
  errorSubtext: {
    fontSize: 14,
    color: Colors.textMuted,
    marginTop: 8,
    marginBottom: 24,
    textAlign: "center",
  },
  retryButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.emerald,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  retryButtonText: {
    color: Colors.bgPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: { paddingBottom: 200 },
  headerGradient: {
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    ...Platform.select({
      ios: {
        shadowColor: Colors.emerald,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  header: {
    padding: 24,
    paddingTop: 40,
    paddingBottom: 32,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginTop: 12,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 16,
    color: Colors.textSecondary,
  },
  riskCard: {
    backgroundColor: Colors.bgCard,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  riskHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  riskTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  riskContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  riskItem: {
    flex: 1,
  },
  riskLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 6,
  },
  riskValue: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  riskDivider: {
    width: 1,
    height: 40,
    backgroundColor: Colors.borderDark,
    marginHorizontal: 16,
  },
  riskBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  riskBadgeText: {
    fontSize: 14,
    fontWeight: "600",
  },
  statsSection: {
    marginTop: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginHorizontal: 20,
    marginBottom: 16,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: Colors.textMuted,
    marginHorizontal: 20,
    marginBottom: 12,
  },
  statsScrollContent: {
    paddingHorizontal: 20,
    gap: 12,
  },
  statCard: {
    width: 120,
    padding: 16,
    borderRadius: 16,
    alignItems: "center",
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  statLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 8,
    fontWeight: "500",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginTop: 4,
  },
  statUnit: {
    fontSize: 11,
    color: Colors.textMuted,
    marginTop: 2,
  },
  timelinesContainer: {
    marginTop: 24,
    paddingHorizontal: 20,
  },
  timelineCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  timelineCardSelected: {
    borderColor: Colors.emerald,
    backgroundColor: "rgba(52, 211, 153, 0.08)",
  },
  recommendedBadge: {
    position: "absolute",
    top: -1,
    right: -1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderTopRightRadius: 14,
    borderBottomLeftRadius: 12,
    gap: 6,
    backgroundColor: Colors.emerald,
  },
  recommendedText: {
    color: Colors.bgPrimary,
    fontSize: 12,
    fontWeight: "600",
  },
  timelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  timelineName: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  difficultyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  difficultyText: {
    color: Colors.bgPrimary,
    fontSize: 11,
    fontWeight: "600",
  },
  rightSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  weeksContainer: {
    alignItems: "center",
    backgroundColor: Colors.bgCardHover,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  weeksNumber: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  weeksLabel: {
    fontSize: 10,
    color: Colors.textMuted,
    marginTop: 2,
  },
  quickMetrics: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  quickMetric: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  quickMetricText: {
    fontSize: 13,
    color: Colors.textSecondary,
    fontWeight: "600",
  },
  selectedIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.borderDark,
    gap: 6,
  },
  selectedText: {
    fontSize: 14,
    color: Colors.emerald,
    fontWeight: "600",
  },
  expandedContainer: {
    overflow: "hidden",
    backgroundColor: Colors.bgCard,
    marginTop: -12,
    marginBottom: 12,
    marginHorizontal: 20,
    borderRadius: 16,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderWidth: 1,
    borderColor: Colors.borderDark,
    borderTopWidth: 0,
  },
  detailedStatsSection: {
    padding: 20,
    backgroundColor: Colors.bgSecondary,
  },
  detailedStatsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: 16,
  },
  detailedStatsScroll: {
    gap: 12,
  },
  detailedStatCard: {
    width: 140,
    backgroundColor: Colors.bgCard,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  detailedStatIcon: {
    width: 48,
    height: 48,
    backgroundColor: Colors.bgCardHover,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  detailedStatLabel: {
    fontSize: 11,
    color: Colors.textMuted,
    marginBottom: 6,
    textAlign: "center",
  },
  detailedStatValue: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  detailedStatUnit: {
    fontSize: 11,
    color: Colors.textMuted,
    marginTop: 2,
  },
  detailsContent: {
    padding: 20,
  },
  tagsContainer: {
    marginBottom: 20,
  },
  tagsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 12,
  },
  tags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    backgroundColor: "rgba(96, 165, 250, 0.15)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  tagText: {
    fontSize: 12,
    color: Colors.blue,
    fontWeight: "500",
  },
  outcomesTag: {
    backgroundColor: "rgba(52, 211, 153, 0.15)",
  },
  outcomesTagText: {
    color: Colors.emerald,
  },
  emphasisContainer: {
    gap: 16,
  },
  emphasisItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: Colors.bgCardHover,
    padding: 16,
    borderRadius: 12,
  },
  emphasisLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 4,
    fontWeight: "600",
  },
  emphasisText: {
    fontSize: 14,
    color: Colors.textPrimary,
    fontWeight: "500",
  },
  notesCard: {
    backgroundColor: Colors.bgCard,
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  notesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  notesTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  noteItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 10,
  },
  noteText: {
    flex: 1,
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  disclaimer: {
    flexDirection: "row",
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    marginHorizontal: 20,
    marginTop: 20,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.3)",
    gap: 12,
  },
  disclaimerText: {
    fontSize: 12,
    color: Colors.amber,
    lineHeight: 18,
  },
  disclaimerBold: {
    fontWeight: "700",
  },
  bottomActions: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: Colors.bgSecondary,
    paddingHorizontal: 20,
    paddingVertical: 8,
    paddingBottom: Platform.OS === "ios" ? 34 : 100,
    borderTopWidth: 1,
    borderTopColor: Colors.borderDark,
    gap: 12,
  },
  customizeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.emerald,
    gap: 8,
  },
  customizeButtonText: {
    fontSize: 16,
    color: Colors.emerald,
    fontWeight: "600",
  },
  startButton: {
    flex: 2,
    borderRadius: 12,
    overflow: "hidden",
  },
  startButtonDisabled: {
    opacity: 0.5,
  },
  startButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    gap: 8,
  },
  startButtonText: {
    fontSize: 16,
    color: Colors.bgPrimary,
    fontWeight: "700",
  },
  headerCard: {
    height: 170,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: Colors.emerald,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  headerImageBg: {
    flex: 1,
    justifyContent: "center",
  },
  headerImageStyle: {
    borderRadius: 20,
  },
  headerOverlay: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleWithBg: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  subtitleWithBg: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  headerUserBox: {
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    padding: 10,
    borderRadius: 16,
  },
  descriptionWithBg: {
    marginTop: 12,
    fontSize: 13,
    color: Colors.textSecondary,
    opacity: 0.9,
  },
});
