import { Colors } from "@/constants/Colors";
import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: Colors.bgPrimary,
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 24,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 14,
    color: Colors.textMuted,
    marginBottom: 20,
    lineHeight: 20,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  newPlanButton: {
    backgroundColor: Colors.emerald,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flex: 1,
    alignItems: "center",
  },
  newPlanButtonText: {
    color: Colors.bgPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  updateButton: {
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: Colors.emerald,
    flex: 1,
    alignItems: "center",
  },
  updateButtonText: {
    color: Colors.emerald,
    fontSize: 14,
    fontWeight: "600",
  },
  planOverview: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  planTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 20,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    textAlign: "center",
  },
  iconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  iconText: {
    fontSize: 12,
  },
  nutritionalTargets: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  sampleMeals: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 100,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  targetIconHeader: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(167, 139, 250, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  targetEmojiHeader: {
    fontSize: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  targetItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bgCard,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  targetIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  targetEmoji: {
    fontSize: 24,
  },
  targetInfo: {
    flex: 1,
  },
  targetName: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  targetAmount: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.emerald,
    marginBottom: 2,
  },
  targetPercentage: {
    fontSize: 12,
    color: Colors.textMuted,
  },
  dayTabs: {
    flexDirection: "row",
    marginBottom: 16,
    gap: 8,
  },
  dayTab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    backgroundColor: Colors.bgCardHover,
    minWidth: width * 0.25,
    alignItems: "center",
  },
  activeTab: {
    backgroundColor: Colors.emerald,
  },
  activeTabText: {
    color: Colors.bgPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  inactiveTabText: {
    color: Colors.textMuted,
    fontSize: 14,
    fontWeight: "600",
  },
  dailySummary: {
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: Colors.emerald,
  },
  dailySummaryText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.emerald,
    marginBottom: 4,
  },
  mealsCount: {
    fontSize: 12,
    color: Colors.emeraldLight,
  },
  mealCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  mealImageContainer: {
    position: "relative",
    height: 160,
  },
  mealImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  mealTypeContainer: {
    position: "absolute",
    bottom: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  mealTypeIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(251, 191, 36, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  mealTypeEmoji: {
    fontSize: 10,
  },
  mealType: {
    fontSize: 11,
    fontWeight: "bold",
    color: Colors.textPrimary,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  caloriesBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  caloriesText: {
    color: Colors.textPrimary,
    fontSize: 11,
    fontWeight: "600",
  },
  mealInfo: {
    padding: 16,
  },
  mealTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 6,
  },
  mealDescription: {
    fontSize: 13,
    color: Colors.textMuted,
    marginBottom: 12,
  },
  nutritionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
    gap: 8,
  },
  nutritionItem: {
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.2)",
  },
  nutritionValue: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.emerald,
  },
  ingredientsLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  ingredientsText: {
    fontSize: 12,
    color: Colors.textMuted,
    lineHeight: 16,
  },
});
