import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/Colors";
import { scale, verticalScale } from "@/utils/responsive";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
    paddingBottom: verticalScale(60), // responsive bottom padding
  },
  header: {
    backgroundColor: Colors.bgCard,
    paddingHorizontal: scale(20),
    paddingVertical: scale(30),
    borderBottomLeftRadius: scale(20),
    borderBottomRightRadius: scale(20),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
    borderTopWidth: 0,
  },
  headerIcon: {
    width: scale(60),
    height: scale(60),
    borderRadius: scale(30),
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: scale(15),
  },
  headerTitle: {
    fontSize: scale(24),
    fontWeight: "bold",
    color: Colors.textPrimary,
    textAlign: "center",
    marginBottom: scale(8),
  },
  headerSubtitle: {
    fontSize: scale(16),
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: scale(22),
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: scale(20),
  },
  section: {
    marginTop: scale(25),
    marginBottom: scale(10),
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: scale(15),
  },
  sectionTitle: {
    fontSize: scale(18),
    fontWeight: "600",
    color: Colors.textPrimary,
    marginLeft: scale(10),
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: scale(10),
  },
  optionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: scale(10),
  },
  goalOption: {
    flex: 1,
    backgroundColor: Colors.bgCard,
    borderRadius: scale(12),
    paddingVertical: scale(20),
    paddingHorizontal: scale(15),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 5,
  },
  goalIcon: {
    fontSize: scale(32),
    marginBottom: scale(8),
  },
  goalLabel: {
    fontSize: scale(14),
    fontWeight: "600",
    color: Colors.textPrimary,
    textAlign: "center",
  },
  inputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: scale(15),
    marginBottom: scale(15),
  },
  inputContainer: {
    flex: 1,
  },
  inputLabel: {
    fontSize: scale(14),
    fontWeight: "500",
    color: Colors.textMuted,
    marginBottom: scale(8),
  },
  textInput: {
    backgroundColor: Colors.bgCard,
    borderRadius: scale(10),
    paddingHorizontal: scale(15),
    paddingVertical: scale(12),
    fontSize: scale(16),
    borderWidth: 1,
    borderColor: Colors.borderDark,
    color: Colors.textPrimary,
  },
  fullWidthInput: {
    backgroundColor: Colors.bgCard,
    borderRadius: scale(10),
    paddingHorizontal: scale(15),
    paddingVertical: scale(12),
    fontSize: scale(16),
    borderWidth: 1,
    borderColor: Colors.borderDark,
    color: Colors.textPrimary,
    width: "100%",
  },
  rateOption: {
    width: (width - scale(60)) / 4 - scale(5),
    backgroundColor: Colors.bgCard,
    borderRadius: scale(10),
    paddingVertical: scale(15),
    paddingHorizontal: scale(8),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
    marginBottom: scale(10),
  },
  rateLabel: {
    fontSize: scale(14),
    fontWeight: "600",
    color: Colors.textPrimary,
    textAlign: "center",
    marginBottom: scale(4),
  },
  rateSubtitle: {
    fontSize: scale(12),
    color: Colors.textMuted,
    textAlign: "center",
  },
  flexibilityOption: {
    width: (width - scale(60)) / 2 - scale(5),
    backgroundColor: Colors.bgCard,
    borderRadius: scale(10),
    paddingVertical: scale(15),
    paddingHorizontal: scale(10),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
    marginBottom: scale(10),
  },
  flexibilityLabel: {
    fontSize: scale(14),
    fontWeight: "600",
    color: Colors.textPrimary,
    textAlign: "center",
  },
  priorityOption: {
    width: (width - scale(60)) / 2 - scale(5),
    backgroundColor: Colors.bgCard,
    borderRadius: scale(10),
    paddingVertical: scale(15),
    paddingHorizontal: scale(10),
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.borderDark,
    marginBottom: scale(10),
  },
  priorityLabel: {
    fontSize: scale(14),
    fontWeight: "600",
    color: Colors.textPrimary,
    textAlign: "center",
  },
  selectedOption: {
    borderColor: Colors.emerald,
    backgroundColor: "rgba(52, 211, 153, 0.1)",
  },
  selectedOptionText: {
    color: Colors.emerald,
  },
  completeButton: {
    backgroundColor: Colors.emerald,
    borderRadius: scale(12),
    paddingVertical: scale(18),
    paddingHorizontal: scale(30),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: scale(30),
    marginBottom: scale(40),
    shadowColor: Colors.emerald,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  completeButtonDisabled: {
    backgroundColor: Colors.textMuted,
    shadowOpacity: 0.1,
    elevation: 2,
  },
  completeButtonText: {
    fontSize: scale(18),
    fontWeight: "bold",
    color: Colors.bgPrimary,
    marginLeft: scale(10),
  },
});
