import { Colors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 24,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerContent: {
    gap: 8,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  headerSubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
  },

  instaHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.bgCard,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderDark,
  },
  instaHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  instaAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Colors.emerald,
  },
  instaUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  instaLocation: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 2,
  },
  // Main image/hero section
  instaMainImage: {
    height: 400,
    marginBottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  mainImageContent: {
    alignItems: "center",
    gap: 16,
  },
  mainImageTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: Colors.textPrimary,
    textAlign: "center",
  },
  mainImageSubtitle: {
    fontSize: 16,
    color: Colors.textSecondary,
    textAlign: "center",
  },
  // Instagram action buttons
  instaActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.bgCard,
  },
  instaActionsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  instaActionBtn: {
    padding: 4,
  },
  // Likes section
  instaLikes: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    backgroundColor: Colors.bgCard,
  },
  instaLikesText: {
    fontSize: 14,
    color: Colors.textPrimary,
  },
  instaLikesBold: {
    fontWeight: "600",
  },
  // Caption section
  instaCaption: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: Colors.bgCard,
  },
  instaCaptionText: {
    fontSize: 14,
    color: Colors.textPrimary,
    lineHeight: 20,
    marginBottom: 8,
  },
  instaCaptionBold: {
    fontWeight: "600",
  },
  instaCaptionHashtags: {
    fontSize: 14,
    color: Colors.emerald,
    lineHeight: 20,
  },
  // Form section
  formSection: {
    paddingTop: 16,
    backgroundColor: Colors.bgPrimary,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingBottom: 60,
  },
  card: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: Colors.borderDark,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: 16,
  },
  inputRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  inputGroup: {
    flex: 1,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.textMuted,
    marginBottom: 8,
  },
  input: {
    backgroundColor: Colors.bgSecondary,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: Colors.textPrimary,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  optionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.bgCardHover,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  optionButtonActive: {
    backgroundColor: Colors.emerald,
    borderColor: Colors.emerald,
  },
  optionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textMuted,
  },
  optionButtonTextActive: {
    color: Colors.bgPrimary,
  },
  optionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  gridOption: {
    width: "30%",
    alignItems: "center",
    backgroundColor: Colors.bgCardHover,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  gridOptionActive: {
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    borderColor: Colors.emerald,
  },
  gridOptionText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textMuted,
    marginTop: 8,
    textAlign: "center",
  },
  gridOptionTextActive: {
    color: Colors.emerald,
  },
  goalGrid: {
    flexDirection: "row",
    gap: 12,
  },
  goalOption: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Colors.bgCardHover,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  goalOptionText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textMuted,
    marginTop: 12,
    textAlign: "center",
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  errorText: {
    flex: 1,
    fontSize: 14,
    color: Colors.red,
  },
  customizeButton: {
    marginBottom: 16,
    marginHorizontal: 16,
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonGradient: {
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.bgPrimary,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  resultsContainer: {
    gap: 16,
  },
  clearButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.bgCardHover,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    marginHorizontal: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  clearButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textMuted,
  },
  summaryCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    marginHorizontal: 16,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  summaryTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  summaryItem: {
    width: "47%",
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    borderRadius: 12,
    padding: 16,
  },
  summaryLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  weeklyBox: {
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  weeklyLabel: {
    fontSize: 14,
    color: Colors.textMuted,
    marginBottom: 4,
  },
  weeklyValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  calorieBox: {
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.2)",
  },
  calorieLabel: {
    fontSize: 14,
    color: Colors.textMuted,
    marginBottom: 8,
  },
  calorieValue: {
    fontSize: 48,
    fontWeight: "bold",
    color: Colors.emerald,
  },
  calorieUnit: {
    fontSize: 16,
    color: Colors.textMuted,
    marginTop: 4,
  },
  macrosTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: 12,
  },
  macrosGrid: {
    flexDirection: "row",
    gap: 12,
  },
  macroItem: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    backgroundColor: Colors.bgCardHover,
  },
  macroLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 8,
    marginBottom: 4,
  },
  macroValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  metricsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  metricItem: {
    flex: 1,
    backgroundColor: Colors.bgCardHover,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  metricLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  tipSection: {
    marginBottom: 16,
  },
  tipTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 8,
    paddingLeft: 4,
  },
  tipText: {
    flex: 1,
    fontSize: 13,
    color: Colors.textMuted,
    lineHeight: 20,
  },
  warningCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.3)",
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: Colors.amber,
    lineHeight: 20,
  },
  workoutItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bgCardHover,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    gap: 12,
  },
  workoutIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: Colors.bgCard,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutDetails: {
    flex: 1,
  },
  workoutLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 4,
  },
  workoutValue: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  startButton: {
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },

  headerCard: {
    height: 170,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: Colors.emerald,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  headerImageBg: {
    width: "100%",
  },
  headerImageStyle: {
    borderRadius: 16,
  },
  headerOverlay: {
    height: 170,
    padding: 16,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },

  titleWithBg: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.textPrimary,
  },

  subtitleWithBg: {
    fontSize: 16,
    fontWeight: "500",
    color: Colors.textSecondary,
    marginTop: 4,
  },

  descriptionWithBg: {
    marginTop: 10,
    fontSize: 14,
    color: Colors.textMuted,
  },

  headerUserBox: {
    backgroundColor: "rgba(52, 211, 153, 0.15)",
    padding: 12,
    borderRadius: 12,
  },
});
