import { Colors } from "@/constants/Colors";
import { StatusBar } from "expo-status-bar";
import { Dimensions, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");
const cardSpacing = 16;
const cardWidth = (width - cardSpacing * 3 - 40) / 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
  },
  header: {
    backgroundColor: Colors.bgCard,
    paddingHorizontal: 20,
    paddingTop: StatusBar.currentHeight ? StatusBar.currentHeight + 10 : 50,
    paddingBottom: 25,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    borderWidth: 1,
    borderColor: Colors.borderDark,
    borderTopWidth: 0,
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  headerDescription: {
    fontSize: 14,
    color: Colors.textMuted,
    marginBottom: 20,
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: Colors.bgCardHover,
    borderRadius: 25,
    padding: 4,
    marginTop: 5,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignItems: "center",
  },
  activeTab: {
    backgroundColor: Colors.emerald,
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textMuted,
  },
  activeTabText: {
    color: Colors.bgPrimary,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  section: {
    marginBottom: 25,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  sectionTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionIcon: {
    marginRight: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.textPrimary,
  },
  viewAllText: {
    fontSize: 14,
    color: Colors.emerald,
    fontWeight: "600",
  },
  summaryCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: Colors.borderDark,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
    marginHorizontal: 2,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
  },
  summaryDivider: {
    width: 1,
    height: 40,
    backgroundColor: Colors.borderDark,
    marginHorizontal: 20,
  },
  summaryValue: {
    fontSize: 28,
    fontWeight: "800",
    color: Colors.emerald,
    marginBottom: 6,
  },
  summaryLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  progressBar: {
    height: 6,
    backgroundColor: Colors.borderDark,
    borderRadius: 3,
  },
  progressFill: {
    height: "100%",
    backgroundColor: Colors.emerald,
    borderRadius: 3,
  },
  storeScrollContainer: {
    paddingRight: 20,
  },
  storeCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 18,
    bottom: 4,
    marginRight: 12,
    width: width * 0.72,
    borderWidth: 1,
    borderColor: Colors.borderDark,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  storeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  storeInfo: {
    flex: 1,
  },
  storeName: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  storeDistance: {
    fontSize: 12,
    color: Colors.textSecondary,
  },
  storeRating: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginLeft: 4,
  },
  storeDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  storeTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.emerald,
    marginBottom: 2,
  },
  storeItems: {
    fontSize: 12,
    color: Colors.textSecondary,
  },
  deliveryTime: {
    fontSize: 12,
    color: Colors.emerald,
    fontWeight: "500",
  },
  productsContainer: {
    paddingBottom: 10,
  },
  productRow: {
    justifyContent: "space-between",
  },
  productCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 14,
    width: cardWidth,
    marginBottom: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.borderDark,
  },
  productImageContainer: {
    position: "relative",
    marginBottom: 10,
  },
  productImage: {
    width: "100%",
    height: 130,
    borderRadius: 12,
    backgroundColor: Colors.bgCardHover,
  },
  discountBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: Colors.red,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountText: {
    color: Colors.bgPrimary,
    fontSize: 10,
    fontWeight: "bold",
  },
  primeBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: Colors.blue,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  primeText: {
    color: Colors.bgPrimary,
    fontSize: 9,
    fontWeight: "bold",
  },
  productInfo: {
    marginBottom: 10,
  },
  productName: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textPrimary,
    marginBottom: 6,
    lineHeight: 16,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  starsContainer: {
    flexDirection: "row",
    marginRight: 4,
  },
  reviewsText: {
    fontSize: 10,
    color: Colors.textSecondary,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.textPrimary,
    marginRight: 8,
  },
  originalPrice: {
    fontSize: 12,
    color: Colors.textSecondary,
    textDecorationLine: "line-through",
  },
  freeDelivery: {
    fontSize: 10,
    color: Colors.emerald,
    fontWeight: "500",
  },
  addToCartButton: {
    backgroundColor: Colors.emerald,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  addToCartText: {
    color: Colors.bgPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  bottomCart: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.bgSecondary,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 22,
    borderTopWidth: 1,
    borderTopColor: Colors.borderDark,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  cartButton: {
    backgroundColor: Colors.emerald,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 18,
    shadowColor: Colors.emerald,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  cartInfo: {
    alignItems: "flex-start",
  },
  cartItems: {
    color: Colors.bgPrimary,
    fontSize: 12,
    opacity: 0.9,
  },
  cartTotal: {
    color: Colors.bgPrimary,
    fontSize: 18,
    fontWeight: "bold",
  },
  cartAction: {
    flexDirection: "row",
    alignItems: "center",
  },
  cartButtonText: {
    color: Colors.bgPrimary,
    fontSize: 16,
    fontWeight: "600",
    marginRight: 8,
  },
});
